### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by Deswer60871** [Cl0udG0d/Fofa-hack#23]
```
Traceback (most recent call last):
  File "C:\Users\Beast\AppData\Local\Temp\tempCodeRunnerFile.python", line 84, in <module>
    main()
  File "C:\Users\Beast\AppData\Local\Temp\tempCodeRunnerFile.python", line 79, in main
    mail_client = Emailnator()
                  ^^^^^^^^^^^^
  File "C:\Users\Beast\AppData\Local\Temp\tempCodeRunnerFile.python", line 19, in __init__
    "x-xsrf-token": self.client.cookies.get("XSRF-TOKEN")[:-3] + "=",
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Cl0udG0d** [comment]
怎会如此，你的运行命令是什么

**Comment by Cl0udG0d** [comment]
我这边使用 python fofa.py -k index 没问题

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/d93be254-67d4-4285-b976-8a83f2ba63b8)

**Comment by Deswer60871** [comment]
no generate new emails 



```
Traceback (most recent call last):
  File "C:\Users\Beast\AppData\Local\Temp\tempCodeRunnerFile.python", line 91, in <module>
    main()
  File "C:\Users\Beast\AppData\Local\Temp\tempCodeRunnerFile.python", line 82, in main
    mail_client = Emailnator()
                  ^^^^^^^^^^^^
  File "C:\Users\Beast\AppData\Local\Temp\tempCodeRunnerFile.python", line 19, in __init__
    "x-xsrf-token": self.client.cookies.get("XSRF-TOKEN")[:-3] + "=",
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function Emailnator.__del__ at 0x000001E8EC2D8040>
Traceback (most recent call last):
  File "C:\Users\Beast\AppData\Local\Temp\tempCodeRunnerFile.python", line 78, in __del__
    if self.email:
       ^^^^^^^^^^
AttributeError: 'Emailnator' object has no attribute 'email'
```

**Comment by Cl0udG0d** [comment]
这个应该是test.py里面的，现在还不是主线用法

**Comment by Cl0udG0d** [comment]
我的项目里面没有调用这个方法

**Comment by Deswer60871** [comment]
could i ask just to get the code working? it worked for me until now and now it stopped working i used it yesterday to create an account i would be very grateful

I'll send a few euros for it

**Comment by Cl0udG0d** [comment]
欧洲人也用微信吗

**Comment by Deswer60871** [comment]
> 欧洲人也用微信吗

google translate is powerful :D

**Comment by Cl0udG0d** [comment]
等我吧，晚上看看这段代码，原来的网站加了访问限制 [www.emailnator.com](http://www.emailnator.com/)

**Comment by Deswer60871** [comment]
yes :D this problem have :DDD

**Comment by Deswer60871** [comment]
now it works again, I don't know why :D did he write something wrong there? and does it fix it? who knows or bug

**Comment by Cl0udG0d** [comment]
我昨天对该部分进行了测试，导致你之前运行失败的原因是目标网站[www.emailnator.com](http://www.emailnator.com/) 部署并开启了 cloudflare防火墙，导致代码中访问获取邮箱的时候被拦截。

不知道为什么网站现在又关闭了防火墙，所以导致代码能够正常运行了

祝你好运
