### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lolminerxmrig** [Cl0udG0d/Fofa-hack#32]
Hi
plz help fixed Error.

[*] LEVEL = 1 , 初始化成功
[*] 爬取延时: 3s
[*] 爬取关键字: title==Ivanti User Portal: Sign In
[*] 爬取结束数量: 2000
[*] 输出格式为: txt
[*] 存储文件名: a52166d748c7be462acd3d96830daa92_1690624424.txt
[*] 是否开启关键字fuzz: False
[*] 是否开启代理: False
[*] 不从文件中读取

[*] 开始运行
[*] 爬取页面为:https://fofa.info/result?qbase64=dGl0bGU9PUl2YW50aSBVc2VyIFBvcnRhbDogU2lnbiBJbg==
[*] 存在数量:0
now search key: title==Ivanti User Portal: Sign In
[*] 已爬取条数 [0]: []
Traceback (most recent call last):
  File "C:\Users\Desktop\ZoomEye\Fofa-hack-2.3.2\Fofa-hack-2.3.2\fofa.py", line 64, in <module>
    main()
  File "C:\Users\Desktop\ZoomEye\Fofa-hack-2.3.2\Fofa-hack-2.3.2\fofa.py", line 60, in main
    fofa.start()
  File "C:\Users\Desktop\ZoomEye\Fofa-hack-2.3.2\Fofa-hack-2.3.2\core\fofaC.py", line 511, in start
    self.fofaSpider(self.search_key, searchbs64, 0)
  File "C:\Users\\Desktop\ZoomEye\Fofa-hack-2.3.2\Fofa-hack-2.3.2\core\fofaC.py", line 329, in fofaSpider
    search_key_modify = self.modifySearchTimeUrl(search_key, index)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\ZoomEye\Fofa-hack-2.3.2\Fofa-hack-2.3.2\core\fofaC.py", line 431, in modifySearchTimeUrl
    time_first = timestamp_list[0].split(' ')[0].strip('\n').strip()
                 ~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by Cl0udG0d** [comment]
Using the latest version, try using this run command

> python fofa.py -k "title=='Ivanti User Portal: Sign In'"

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/c18fd0df-8f0b-43c3-a22e-6a2eb4ddc168)
