### ISSUE TITLE
使用报错 不清楚是我本地的原因 还是fofa服务器的问题

### ISSUE THREAD

**Issue by Lolydawn** [Cl0udG0d/Fofa-hack#63]
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 700, in urlopen
  File "urllib3\connectionpool.py", line 996, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 499, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fofa.info', port=443): Max retries exceeded with url: /result?qbase64=aW5kZXggJiYgY291bnRyeT0iQ04i (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fofa.py", line 113, in <module>
    main()
  File "fofa.py", line 109, in main
    fofa.start()
  File "core\fofaMain.py", line 566, in start
    searchbs64, countnum = self.getFofaKeywordsCount(self.search_key)
  File "core\fofaMain.py", line 119, in getFofaKeywordsCount
    html = requests.get(url="https://fofa.info/result?qbase64=" + searchbs64,
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='fofa.info', port=443): Max retries exceeded with url: /result?qbase64=aW5kZXggJiYgY291bnRyeT0iQ04i (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
[3892] Failed to execute script 'fofa' due to unhandled exception!

**Comment by Cl0udG0d** [comment]
你是不是运行的时候开代理了

**Comment by Lolydawn** [comment]
明白了师傅 不过为什么他会被代理影响到呢 正常来说代理不是分情况的吗

**Comment by Cl0udG0d** [comment]
看起来是urllib3 库对代理的处理有问题 ，需要下降到特定的版本去 下个版本我会把urllib3降级到1.25.11尝试解决该问题
